# ambiente local
apiVersion: v1
kind: Secret
metadata:
  name: autoshop-secrets
  namespace: autoshop
type: Opaque
stringData:
  JWT_SECRET: "autoshop-secret-dev"
  EMAIL_WEBHOOK_SECRET: "autoshop-webhook-dev"
  DB_PASSWORD: "autoshop"
